name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Push to deploy branch
      run: |
        git push -f origin deploy
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: spos
        host: 172.105.41.129
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: 'cd /var/www/spos.cc && ./server_deploy.sh'
